name: GitHub CI
run-name: ${{ github.actor }} ran the workflow ${{ github.workflow }} on ${{ github.event_name }}🚀

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up and install dependencies
        uses: ./.github/actions/setup-and-install

      - name: Set up environment file for development
        if: github.ref == 'refs/heads/dev'
        run: echo "${{ secrets.DEVELOPMENT_ENV }}" > .env

      - name: Set up environment file for production
        if: github.ref == 'refs/heads/main'
        run: echo "${{ secrets.PRODUCTION_ENV }}" > .env

      - name: Generate types
        run: pnpm api:typegen

      - name: Build project
        run: pnpm run build

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Set up and install dependencies
        uses: ./.github/actions/setup-and-install

      - name: Set up environment file for development
        if: github.ref == 'refs/heads/dev'
        run: echo "${{ secrets.DEVELOPMENT_ENV }}" > .env

      - name: Set up environment file for production
        if: github.ref == 'refs/heads/main'
        run: echo "${{ secrets.PRODUCTION_ENV }}" > .env

      - name: Install Playwright browsers if not cached
        run: pnpm exec playwright install
        if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'

      - name: Install system dependencies for Playwright
        run: |
          sudo apt-get update
          sudo apt-get install -y libwoff1 libopus0 libvpx7 libevent-2.1-7

      - name: Run unit tests
        run: pnpm run test:unit

      - name: Run end-to-end tests
        run: pnpm run test:e2e

